### ISSUE TITLE
Java 8 doesn't run on recent Debian Jessie

### ISSUE THREAD

**Issue by bitzl** [ansiblebit/launchpad-ppa-webupd8#6]
Java won't start on a recent Debian Jessie if installed using this role. To get a running install, I did
- purge the installed Java
- Change Ubuntu distribution in apt sources from `trusty` to `xenial`
- Install Java again

**Comment by steenzout** [comment]
@bitzl I see you closed the issue.

is this a problem or not?

**Comment by bitzl** [comment]
@steenzout I've closed this issue because it got the impression that it was a problem with my testing VM and not this Ansible role. I could verify this now - it was some weird problem with my VM and _no issue_ with this role.
