### ISSUE TITLE
ansible-galaxy install old version (v3.9.4) instead of 4.14.0

### ISSUE THREAD

**Issue by roumano** [ansiblebit/launchpad-ppa-webupd8#7]
ansible-galaxy install ansiblebit.launchpad-ppa-webupd8
- downloading role 'launchpad-ppa-webupd8', owned by ansiblebit
- downloading role from https://github.com/ansiblebit/launchpad-ppa-webupd8/archive/v3.9.4.tar.gz
- extracting ansiblebit.launchpad-ppa-webupd8 to /home/fedora/svn/ansible/roles/ansiblebit.launchpad-ppa-webupd8
- ansiblebit.launchpad-ppa-webupd8 was installed successfully

Maybe it's linked to the name of old version as it's contents a "v" ....

**Comment by steenzout** [comment]
same problem as https://github.com/ansible/galaxy-issues/issues/251 and https://github.com/ansiblebit/oracle-java/issues/39.

**Comment by steenzout** [comment]
@roumano as a note, for Fedora you don't need to install this role.

**Comment by roumano** [comment]
Hi,
Fedora is only my workstation.
Managing rhel6/rhel7, OEL, Centos, Amazon Linux and Debian
Tkx for the issue in galaxie

**Comment by steenzout** [comment]
this has been fixed:
```
$ ansible-galaxy -vv install ansiblebit.launchpad-ppa-webupd8
No config file found; using defaults
- downloading role 'launchpad-ppa-webupd8', owned by ansiblebit
- downloading role from https://github.com/ansiblebit/launchpad-ppa-webupd8/archive/4.14.0.tar.gz
```
